# ASSIGNMENT 3

## TASK 1

### Q 1

In [1]:
def divide(a,b):
    try:
        result = a/b
    except:
        print("Error: Divide by zero error")
    else:
        return 
    
    
print(divide(3,4))
print(divide(5,0))

None
Error: Divide by zero error
None


### Q 2

In [2]:
subjects = ["Americans","Indians"]
verbs = ["play","watch"]
objects = ["baseball","cricket"]

sentences = []
for s in subjects:
    for v in verbs:
        for o in objects:
            sentences.append(s + ' ' + v + ' ' +o)
            
sentences

['Americans play baseball',
 'Americans play cricket',
 'Americans watch baseball',
 'Americans watch cricket',
 'Indians play baseball',
 'Indians play cricket',
 'Indians watch baseball',
 'Indians watch cricket']

## TASK 2

### Q 1

In [3]:
import numpy as np
def func(iterable,N, increasing):
    vanmat = np.array(np.zeros((N,len(iterable))))
    for j in range(0,N):
        for index,val in enumerate(iterable):
            if increasing == True:
                vanmat[j][index] = val**j
            else: 
                vanmat[j][index] = val**(N-j-1)
    vanmat = np.array(vanmat)
    vanmat = vanmat.T
    return vanmat

In [4]:
result = func([1,2,3,4,5],4,False)
print(result)

[[  1.   1.   1.   1.]
 [  8.   4.   2.   1.]
 [ 27.   9.   3.   1.]
 [ 64.  16.   4.   1.]
 [125.  25.   5.   1.]]
